version: "3.8"

services:
  server:
    build: .
    container_name: smartbus-server
    command: python3 server/main.py
    ports:
      - "5000:5000/udp"
      - "5001:5001/udp"
      - "6000:6000/udp"
      - "7000:7000"
      - "8000:8000"
    networks:
      busnet:
        ipv4_address: 172.28.0.10

  attacker:
    build: .
    container_name: smartbus-attacker
    command: sleep infinity
    networks:
      busnet:
        ipv4_address: 172.28.0.30
    depends_on:
      - server

networks:
  busnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
